### ISSUE TITLE
Mandatory parameter(s) missed or blank: dlat and dlon are required for BMW vehicles

### ISSUE THREAD

**Issue by mnbf9rca** [thickey256/iRemote-PHP#3]
I have a 3 series. I'm not using your API, but wondered if you'd noticed this too. When I make a call to /webapi/v1/user/vehicles/'.$vin.'/status i get:

```
{
  "error": {
    "code": 500,
    "description": "(SmartPhoneUtil-A-101) Mandatory parameter(s) missed or blank: dlat and dlon are required for BMW vehicles!"
  }
}
```

if i add the lat + long of my home as querystring paramaters (`/?dlat=x&dlon=y`) it works but i don't get a lot of other data (e.g. door status) although i guess that's to do with the options available on my car:

```
{
  "vehicleStatus": {
    "vin": "(my VIN)",
    "updateTime": "2016-08-28T17:52:44+0200",
    "position": {
      "lat": 5x.xxxxx,
      "lon": -y.yyyyy,
      "status": "OK"
    }
  }
}
```

Here's the problem - if the car is more than half a KM from home, when i get:

```
{
  "vehicleStatus": {
    "vin": "(my VIN)",
    "updateTime": "2016-08-28T17:52:44+0200",
    "position": {
      "status": "TOO_FAR_AWAY"
    }
  }
}
```

(not sure what the "updateTime" value is as that's clearly a long time ago).

**Comment by thickey256** [comment]
Hi @mnbf9rca,

It looks like the functionality for the 3 series and i3(and i8 I assume) is quite different.  With the native mobile app are you able to view the vehicle status when you/it is parked 'TOO_FAR_AWAY'?

With the i3 at least it doesn't require any location information and I'm able to interact with the car when it's not at home.

Sorry I can't be any help for you.

**Comment by mnbf9rca** [comment]
I get the error with the official BMW mobile app too. And if i try to use the i app to access my car, it doesnt let me as i dont have the right sort of car (although looking at the app traffic, the consumer key + secret are the same for both, so this is a client-side difference). The description for one instance of the app on Google Play (https://play.google.com/store/apps/details?id=us.bmw.remote&hl=en_GB) says "Note: Vehicle Finder only works if the vehicle is within 0.6 miles (1 kilometer) from the iPhone and the vehicle’s ignition is turned off". I've found though that vehicle finder DOES work when the engine is running, but the location thing is true.

**Comment by thickey256** [comment]
@mnbf9rca I simply perform "gimme the car status" call and the vehicle location is part of that, along with fuel levels/battery levels etc etc.

If you are getting the error with the app then this tells you two things. (1)  It probably doesn't matter what you try it's not going to work. (2) It could be a glitch in your account, perhaps talk to BMW and say you get this error with the app (I would forget to mention that you are trying to access the data a different way :grin:)

**Comment by mnbf9rca** [comment]
it's definitely expected behavior. Just interesting that it doesnt happen with your model of car. Might be different behaviour with older and newer app client key/secret. I'll email you to compare keys...
